[pytest]
cache_dir = .cache/pytest
pythonpath = src
addopts = --cov=src --cov-report=term-missing -q
asyncio_mode = auto
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::pydantic.warnings.PydanticDeprecatedSince211
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning
